resume/src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Enum\DeclarationTypeEnum;
use App\Enum\InvoicePaymentTypeEnum;
use App\Enum\InvoiceStatusEnum;
use App\Repository\InvoiceRepository;
use DateInterval;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Stringable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
#[UniqueEntity('number')]
class Invoice implements Stringable
{
    final const NUMBER_DATE_FORMAT = 'Ym-';
    final const TAX_MULTIPLIER = 0.2;
    final const DUE_INTERVAL_1M = 'P1M';
    /** @var array user friendly named type */
    final const DUE_INTERVALES = [
        '30 days end of month' => self::DUE_INTERVAL_1M,
    ];
    final const TJM_DEFAULT = 400;
    final const LIMIT_AE_TVA = 33200;
    final const LIMIT_AE = 70000;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private int $id;

    #[ORM\Column(type: Types::STRING, length: 255, unique: true)]
    private ?string $number = null;

    #[ORM\ManyToOne(targetEntity: Company::class, cascade: ['persist'], inversedBy: 'invoices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\ManyToOne(targetEntity: Experience::class, cascade: ['persist'], inversedBy: 'invoices')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Experience $experience = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $payedAt = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $totalHt = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $totalTax = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $object = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $tjm = null;

    #[ORM\Column(type: Types::STRING, nullable: true, enumType: InvoicePaymentTypeEnum::class)]
    private ?InvoicePaymentTypeEnum $payedBy = null;

    #[ORM\Column(type: Types::STRING, nullable: true, enumType: InvoiceStatusEnum::class)]
    private ?InvoiceStatusEnum $status = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $dueInterval = null;

    /**
     * @var Collection<Activity>
     */
    #[ORM\OneToMany(mappedBy: 'invoice', targetEntity: Activity::class, cascade: ['persist', 'remove'])]
    private Collection $activities;

    #[ORM\ManyToOne(targetEntity: Period::class, inversedBy: 'invoices')]
    private ?Period $period = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 1, nullable: true)]
    private ?float $daysCount = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $extraLibelle = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $extraHt = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $reference = null;

    public function __construct()
    {
        $this->daysCount = 0;
        $this->tjm = self::TJM_DEFAULT;
        $this->createdAt = new DateTime();
        $this->object = "Prestation de développement web - " . (new DateTime())->format('Y-m');
        $this->setNumber((new DateTime())->format(Invoice::NUMBER_DATE_FORMAT));
        $this->setPayedBy(InvoicePaymentTypeEnum::Transfert);
        $this->status = InvoiceStatusEnum::Draft;
        $this->dueInterval = 'P1M';
        $this->activities = new ArrayCollection();
    }

    public function updateHt(): void
    {
        $this->totalHt = $this->tjm * $this->daysCount + $this->extraHt;
    }

    public function isCredit(): bool
    {
        return $this->getTotalHt() < 0;
    }

    public function getTotalHt(): ?string
    {
        return $this->totalHt;
    }

    public function setTotalHt(?string $totalHt): self
    {
        $this->totalHt = $totalHt;
        if (!$this->getDaysCount() && $this->getTjm()) {
            $this->setDaysCount($this->getTotalHt() / $this->getTjm());
        }

        return $this;
    }

    public function getDaysCount(): ?float
    {
        return $this->daysCount;
    }

    public function setDaysCount(?float $daysCount): self
    {
        $this->daysCount = $daysCount;
        if (!$this->getTotalHt()) {
            $this->setTotalHt($this->getDaysCount() * $this->getTjm());
        }

        return $this;
    }

    public function getTjm(): ?int
    {
        return $this->tjm;
    }

    public function setTjm(?int $tjm): self
    {
        $this->tjm = $tjm;

        return $this;
    }

    public function isEditable(): bool
    {
        return !$this->getPayedAt() && $this->getStatus() === InvoiceStatusEnum::Draft;
    }

    public function getPayedAt(): ?DateTimeInterface
    {
        return $this->payedAt;
    }

    public function setPayedAt(?DateTimeInterface $payedAt): self
    {
        $this->payedAt = $payedAt;

        return $this;
    }

    public function getStatus(): ?InvoiceStatusEnum
    {
        return $this->status;
    }

    public function getStatusOrder(): int
    {
        return match ($this) {
            InvoiceStatusEnum::Draft => 0,
            InvoiceStatusEnum::Waiting => 1,
            InvoiceStatusEnum::Payed => 2,
        };
    }

    public function setStatus(?InvoiceStatusEnum $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTotalNet(): float
    {
        return floatval($this->totalHt) * (1 - Declaration::SOCIAL_NON_COMMERCIALE);
    }

    /**
     * @param Activity[] $activities
     */
    public function importActivities(array $activities): void
    {
        $dayCount = 0;

        foreach ($activities as $activity) {
            $activity->setInvoice($this);
            $dayCount += $activity->getValue();
        }

        $this->setDaysCount($dayCount);
    }

    public function getFilename(): string
    {
        return $this->getNumber() . '.pdf';
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getExperienceCompany(): string
    {
        return $this->experience ? $this->getExperience()->getCompany()->getDisplayName() : '';
    }

    public function getExperienceName(): string
    {
        return $this->experience ? $this->getExperience()->__toString() : '';
    }

    public function __toString(): string
    {
        return $this->getNumber();
    }

    public function getExperience(): ?Experience
    {
        return $this->experience;
    }

    public function setExperience(?Experience $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getCreatedAtYear(): int
    {
        return $this->createdAt->format('Y');
    }

    public function getPayedAtYear(): int
    {
        return $this->payedAt->format('Y');
    }

    public function getCreatedAtQuarter(): int
    {
        return ceil($this->createdAt->format('n') / 3);
    }

    public function getPayedAtQuarter(): int
    {
        return ceil($this->payedAt->format('n') / 3);
    }

    public function getTotalTtc(): ?string
    {
        return $this->getTotalHt() + $this->getTotalTax();
    }

    public function getTotalTax(): ?string
    {
        return $this->totalTax;
    }

    public function setTotalTax(?string $totalTax): self
    {
        $this->totalTax = $totalTax;

        return $this;
    }

    public function getObject(): ?string
    {
        return $this->object;
    }

    public function setObject(?string $object): self
    {
        $this->object = $object;

        return $this;
    }

    public function getPayedBy(): ?InvoicePaymentTypeEnum
    {
        return $this->payedBy;
    }

    public function setPayedBy(InvoicePaymentTypeEnum $payedBy): self
    {
        $this->payedBy = $payedBy;

        return $this;
    }

    public function getPayedByName(): ?string
    {
        return $this->payedBy->toString();
    }

    public function getStatusName(): string
    {
        return $this->status->toString();
    }

    /**
     * @throws Exception
     */
    public function getDueAt(): ?DateTime
    {
        if (!$this->getCreatedAt() || !$this->getDueInterval()) return null;

        $createdAt = $this->getCreatedAt();
        $lastDayOfMonth = new DateTime($createdAt->format('Y-m-t'));
        $firstDayOfNextMonth = (clone $lastDayOfMonth)->add(new DateInterval('P1D'));
        return new DateTime($firstDayOfNextMonth->format('Y-m-t'));
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDueInterval(): ?string
    {
        return $this->dueInterval;
    }

    public function setDueInterval(?string $dueInterval): self
    {
        $this->dueInterval = $dueInterval;

        return $this;
    }

    /**
     * @return Collection<Activity>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

resume/templates/fields/form.html.twig
{# note that the Twig block name starts with an uppercase letter
   ('_Product_...' instead of '_product_...') because the first part
   of the block name is the unmodified entity name #}
{% block invoices %}
    {% set CompanyType = enum('App\\Enum\\CompanyTypeEnum') %}
    <style>
        .table {
            color: var(--form-label-color);
        }
    </style>
    <table class="table">
        <thead>
        <tr>
            {% set totalColspan = 2 %}
            {% if source == 'declaration' %}
                {% set totalColspan = totalColspan + 1 %}
                <th scope="col">Entreprise</th>
            {% endif %}
            {% if source == 'company' and form.parent.vars.value.type == CompanyType.ESN %}
                {% set totalColspan = totalColspan + 1 %}
                <th scope="col">Client</th>
            {% endif %}
            <th scope="col">Numéro</th>
            <th scope="col">Payé le</th>
            <th scope="col" class="text-right">HT</th>
            <th scope="col" class="text-right">TVA</th>
        </tr>
        </thead>
        <tbody>
        {% set totalHt = 0 %}
        {% set totalTax = 0 %}
        {% for invoice in data %}
            <tr>
                {% if source == 'declaration' %}
                    <td>{{ invoice.company }}</td>
                {% endif %}
                {% if invoice.company.type == CompanyType.ESN %}
                    <td>{{ invoice.experienceCompany }}</td>
                {% endif %}
                <td>{{ invoice.number }}</td>
                <td>{{ invoice.payedAt | date('d/m/Y') }}</td>
                <td class="text-right">{{ invoice.totalHt | format_currency('EUR') }}</td>
                <td class="text-right">{{ invoice.totalTax ? (invoice.totalTax | format_currency('EUR')) : '' }}</td>
            </tr>
            {% set totalHt = totalHt + invoice.totalHt %}
            {% set totalTax = totalTax + invoice.totalTax %}
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td colspan="{{ totalColspan }}" class="text-right">Total :</td>
            <td class="text-right">{{ totalHt | format_currency('EUR') }}</td>
            <td class="text-right">{{ totalTax | format_currency('EUR') }}</td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

{% block _Declaration_invoices_widget %}
    {% set source = 'declaration' %}
    {{ block('invoices') }}
{% endblock %}
{% block _Company_invoices_widget %}
    {% set source = 'company' %}
    {{ block('invoices') }}
{% endblock %}